name: Update Version for the Java Tracer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *' # 2:00 PM UTC which is morning in New York

jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for getting the required OIDC token from GitHub
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/datadog-aas-linux
          policy: self.tracer-update.create-pr

      - name: Modify build-packages
        id: version
        run: |
          python .github/workflows/datadog_wrapper_tracer_update.py --tracer java

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          branch: "java-tracer-version-bump"
          commit-message: "${{steps.version.outputs.pr_title}}"
          delete-branch: true
          title: "${{steps.version.outputs.pr_title}}"
          body: "${{steps.version.outputs.pr_body}}"

      - name: Display output
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"


