# Disabled in favor of
# https://github.com/DataDog/serverless-self-monitoring/blob/main/self_monitor/azure/launch.sh

name: update_self_monitoring_apps

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  update_apps:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      packages: write
    # Set the env for Azure managed identity federated credentials for OIDC
    # https://github.com/marketplace/actions/azure-login#login-with-openid-connect-oidc-recommendeda
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Azure login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure Web Apps
        uses: azure/cli@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956 # v2.2.0
        with:
          inlineScript: |
            az webapp deploy --resource-group "serverless-aas-linux" --name "serverless-dotnet6-self-monitoring" --src-path ./datadog_wrapper --type=startup
            az webapp deploy --resource-group "serverless-aas-linux" --name "serverless-java-springboot-self-monitoring" --src-path ./datadog_wrapper --type=startup
            az webapp deploy --resource-group "serverless-aas-linux" --name "serverless-node-express-self-monitoring" --src-path ./datadog_wrapper --type=startup
            az webapp deploy --resource-group "serverless-aas-linux" --name "serverless-php-laravel-self-monitoring" --src-path ./datadog_wrapper --type=startup
            az webapp deploy --resource-group "serverless-aas-linux" --name "serverless-py-django-self-monitoring" --src-path ./datadog_wrapper --type=startup
            az webapp deploy --resource-group "serverless-aas-linux" --name "serverless-tomcat-self-monitoring" --src-path ./datadog_wrapper --type=startup


